// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqxotpervbbmgtcwolgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxeG90cGVydmJibWd0Y3dvbGdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NjE0NDcsImV4cCI6MjA2MDAzNzQ0N30.m7rLlyFCO0ZSxpcOHyrXvZrVcol0lx0vpNm6GLC4Q5s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);